#!/usr/bin/env python
import commands
import sys

def usage():
    print "Usage: drbd_stats [discovery|dstate|cstate] RESOURCE"
    sys.exit(1)

if len(sys.argv) < 2 or len(sys.argv) > 3:
    usage()

command = sys.argv[1]

if command in ['dstate','cstate']:
   resource = sys.argv[2]
   print commands.getoutput('drbdadm {0} {1}'.format(command,resource))
   sys.exit(0)

if command == 'discovery':
       data = ''
       resources = commands.getoutput("/usr/sbin/drbd-overview | /usr/bin/sed -n 's/.*[0-9]:\([a-z0-9\/]*\)\ .*/\\1/p'").split('\n')
       for res in resources:
           data += '{ "{#RESOURCE_NAME}": "%s" },' % res
       print '{ "data": [ %s ] }' % data[0:-1]
       sys.exit(0)

usage()
